### ISSUE TITLE
serverconfig.xml contains deprecated options

### ISSUE THREAD

**Issue by Laura7089** [cbrgm/7days-docker#3]
The `serverconfig.xml` file in the repo contains values which have been deprecated by the game, and cause it to abort on run.

**Comment by Laura7089** [comment]
Tentatively, the affected options appear to be:

- `DisableNat`
- `FriendlyFire`
- `ServerIsPublic`
- `NightPercentage`
- `EnemySpawnMode`
- `EnemySenseMemory`
- `LootTimer`
- `CraftTimer`

I'll run some more thorough tests when I get the time.

This is a difficult issue to solve with future-proofing since the game download doesn't seem to include a default server config file and it won't generate it on start.

**Comment by cbrgm** [comment]
Merged #4
